use_frameworks!

target 'FLCommonLibrary_Example' do
  pod 'FLCommonLibrary', :path => '../'

  target 'FLCommonLibrary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
